import { Inter } from "next/font/google";
import "../_styles/reset.css";
import "../_styles/global.css";
import Header from "@/_components/header";
import Footer from "@/_components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "next-films",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="container">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
